name: Publish Python Package to PyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to publish (e.g., v0.4.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lybic
    permissions:
      id-token: write # Required for trusted publishing with OIDC

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install twine wheel setuptools

    - name: Build package
      run: make build

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.LYBIC_PYPI_KEY }}
      run: make publish
